### ISSUE TITLE
Camp profile page

### ISSUE THREAD

**Issue by natekonimbo** [Midburn/spark#116]
Profile page for each camp, presents the published details, for example:

- name
- description
- contact person
- facebook page
etc

profile page will be visible with permanent link to the public

can be implemented by the Camps API

**Comment by OriHoch** [comment]
@natekonimbo more info needed..

**Comment by asihud** [comment]
@OriHoch 

What is needed is that the link:
http://localhost:3000/he/camps/1

which describes the camp, will be available from the outside (even if no one logged in)
ofcourse, all edit options are disabled.
basically, is to take this link, and disable all options of menu, when user is not logged in, or even create the same jade file, but with different header & footer.

**Comment by OriHoch** [comment]
@asihud  - when I go to this page I get an error
http://sparkstaging.midburn.org/he/camps/1
also, I'm not sure I understand what the outcome is supposed to be.. does it require UI design? is it just a matter of permissions? 

it would be helpful if  you could write precise reproduction steps (for example - open URL, click on this icon, look at that image) - then the expected behavior (what you expect to see / how you expect it to work) and finally the actual behavior (what actually happens, would be helpful to add a screenshot)
