### ISSUE TITLE
NodeJS & Sqlite3 versions issue

### ISSUE THREAD

**Issue by natekonimbo** [Midburn/spark#156]
> The sqlite3 module works with Node.js v0.10.x, v0.12.x, v4.x, and v5.x.
quote from https://www.npmjs.com/package/sqlite3

We run Node v7 now.
Should downgrade version to support this middleware.

:)

**Comment by OriHoch** [comment]
on github it says they support v7.x as well

https://github.com/mapbox/node-sqlite3

most likely the details on npmjs are not up to date

if you had a specific problem with it, try installing the version from github instead to see if that fixes it

**Comment by natekonimbo** [comment]
@OriHoch i see. so we can set `package.json` to pull this package from GitHub?

hence the Travis-CI failing [log](https://travis-ci.org/Midburn/Spark#log-container)

**Comment by OriHoch** [comment]
@natekonimbo you can install from github (sqlite3 installation details how to do it) but I'm not sure that will solve the problem on travis

I don't see indication that the problem is related to node version.. 

I see a lot of other changes done to dependencies and installation process, sqlite3 worked fine in the past, I see no reason for it to stop working now

**Comment by OriHoch** [comment]
If I had to guess, I would guess the replacing of npm with yarn is a good candidate for causing this bug..

**Comment by netanelben** [comment]
Fixed.

travis.yml missing node version
