### ISSUE TITLE
A few questions about admin-created user and Drupal logins

### ISSUE THREAD

**Issue by ripper234** [Midburn/spark#220]
I'm trying to login to the system through the `a` user created via `/dev/create-admin`.

It appears the login logic always goes to the live drupal system, and doesn't find any `a` users there, and fails the login.
So, this login method doesn't currently work (tried it on a clear local system).

Since the `/dev/create-admin` endpoints still exists in the code, it being broken is confusing to a new developer that tries to use it.

A few questions:

1. Why is Drupal queried before the local user table? Shouldn't we query the local users table before drupal?
2. As things are now, do we prefer investing time in fixing this flow so the admin-created user works? Or alternatively, should we just remove admin-created users entirely? (We shouldn't leave things as they are now, it's broken)
3. If we want to fix admin-created users - how should we do it, in relation to drupal logins?

**Comment by asihud** [comment]
@ripper234 -
Ron, this because we want people to login the spark thru their profile system.
until the spark system will not be the main authentication server, this is the issue.
we do not save the passwords on the local server. then again, waiting for it to become the main system.
i think the admin-created should be deprecated, or at least it would update special emails to gain admin role, automatically.
we do need to put a switch to enable/disable this (if we want to have the spark as a solution that not relay on the midburn project of course).

**Comment by asihud** [comment]
@ripper234 ,
can we closed this issue?
