### ISSUE TITLE
Camps data should be pre-populated on a new enviornment

### ISSUE THREAD

**Issue by ripper234** [Midburn/spark#284]
To make it easy on new developers, we should make it easy for them to start working on camps.

The following steps on a clean environment should allow a developer to login and see a populated list of camps.

```
(on a fresh git clone)
npm install
knex migrate:latest
npm start
```

**Comment by asihud** [comment]
not relevant.

**Comment by OriHoch** [comment]
@asihud is it resolved? is it now easy for new developers to start working on camps?
please write why you think it's not relevant
I also had this issue - could not start working on camps

**Comment by asihud** [comment]
We do not have the man power at the moment, to split between the camps & the sparks.
all environment should be changed.
if you volunteer to take this issue and do the split and everything, go ahead, you will be blessed.

as managing the #camps module, i need to make sure, that all related issues to camps are submitted to someone who can take care of the issue, otherwise it is pointless to keep them open, and have issues.

this is also big issue, it is require to have someone who knows both spark and camps, and know how to split everything into two projects.

Also, the decision is not github issue, but a question should be discussed in the wendsday meeting, regard the structure of all Midburn project.

**Comment by asihud** [comment]
no, it is not resolved.
do you suggest to populate all camps data within the project ?

**Comment by OriHoch** [comment]
yes, we should have some process that loads test data (AKA fixtures)
this allows for:
* quick start for new developers
* reliable reproduction steps - if you reproduce bugs on the same data, you have less problems of "it works on my machin"
* use in unit tests - it is easier to write tests if you use the same data for both dev and test

I think @ripper234 even wrote some perliminary code to help do that in this PR - #282

**Comment by ripper234** [comment]
#282 is not really related to this issue.

However this issue is very relevent. It's very difficult to get started working with the camps module. We should strive that our dev env will be fully populated with data after the steps described above.

Currently I'm not even sure what's the process to get started working on camps, it's not documented anywhere, not to mention not automated.

We don't need all camps, just enough mock data to get started working.
And access to an admin user who can add/edit/remove camps - this is also nonexistent today.

Think someone who just discovered the project and wants to contribute - we should not make them jump through any hoops in order to get the system up and running.

**Comment by amotenko** [comment]
have seeding now
