### ISSUE TITLE
Spark should have a monitoring and alerting solution

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#311]
At the most basic level we need something that monitors our various services and sends alerts in the relevant slack channels if anything is down.

At a more advanced level the monitoring service can attempt restarting the fallen service.

**Comment by amotenko** [comment]
Also consider load balancing and auto-scaling

**Comment by ArtyomKa** [comment]
I tested [StatusCake](https://www.statuscake.com/) monitoring service. Looks like it works... Got slack integration to work it sends messages on #sparksystem_status channel I opened for that purpose.

The problem is that the free version is allowing only one account to manage the monitoring settings. So we either use some system account (we probably have one for managing the Amazon services), get a basic paid version or find another alternative.

**Comment by OriHoch** [comment]
@amotenko - regarding load balancing and auto-scaling - not sure what you meant..
what I meant was that we need to have the servers support auto-scaling and load-balancing (which we don't at the moment)
once servers support that, monitoring should monitor it but that's only secondary to actually having autoscaling..

**Comment by amotenko** [comment]
I meant what you meant. That we should probably have the amazon load balancer and auto scaling enabled, and those should report to the monitoring system.
@OriHoch

**Comment by OriHoch** [comment]
cool, worth to open a separate issue for that and write what the high-level requirements are for this functionality

**Comment by amotenko** [comment]
will do

**Comment by amotenko** [comment]
we now have at least status cake
