### ISSUE TITLE
Travis should run migrations on mysql-server also.

### ISSUE THREAD

**Issue by ArtyomKa** [Midburn/spark#332]
### Overview of the problem
Some of the migrations pass on dev environments (sqlite) but fail on staging-production. Most of the developers don't run local versions of mysqlserver, so we only discover that we have broken migrations when we are about to deploy a version to either staging, which is probably too late...

### Steps to Reproduce
In current code version v2.2.3 migrations pass on dev. stations and travis but fail in staging (see #330 )

### Expected behavior
Travis should run migrations on mysql server, migrations will fail and merging to master should be blocked.

### Actual behavior
Travis runs migrations on sqlite and they pass.

**Comment by OriHoch** [comment]
should be relatively easy to do - need to modify .travis.yml to:
- [ ] setup mysql  - this is well documented on travis and elsewhere
- [ ] modify the .env file used by travis to use the mysql DB instead of the default sqlite
  - this can be done by creating a .env.travis file and have the travis scripts copy that to .env file

**Comment by ArtyomKa** [comment]
OK. Thanks I'll do that. But I want to fix the migrations locally first...

**Comment by OriHoch** [comment]
@ArtyomKa I'll work on that, maybe help with the migrations as well

**Comment by OriHoch** [comment]
#333
