### ISSUE TITLE
test environment should be open to the public

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#372]
### reproduction steps
* be a developer that looks for open source project to contribute to
* browse github for interesting projects
* find Midburn/Spark repository
* look at the issues list
* find a nice starter issue which looks easy to fix
* look at the reproduction steps of this issues - find a URL to staging environment
* click on this link

#### expected
* go to the staging environment, see the problem
* read the [contribution guide](https://github.com/Midburn/Spark/blob/master/CONTRIBUTING.md)
* find at the bottom of contribution guide, link to [development guide](https://github.com/Midburn/Spark/blob/master/docs/development/README.md)
* install the development environment
* fix the issue
* open a pull request
* great success

#### actual
* be frustrated that you get a login page
* WTF?
* go help another project (I recommend [knesset-data](https://github.com/hasadna/knesset-data) :stuck_out_tongue_winking_eye: )

**Comment by OriHoch** [comment]
Ran Goldi:

> I agree, but that being said, we had over 100+ users that thought this is the real Spark system and performed all the Theme Camps actions int he staging… I would just rather replace the homepage with a clear popup or message, but for now this does the trick.

**Comment by omerpines** [comment]
Expected:
1. Developers should not work on staging but in their local environment.
2. Staging should serve the QA and tech team (mainly management).
3. Staging should have an open limited demo user (predefined for that purpose) for anyone to use (can indicate this on the login screen). This is to prevent access to sensitive information in the system (e.g. personal information) 
4. Super user to the system should be available to designated Tech team members only for testing and review. For security reasons, SU username and password should be kept secret and not be in slack or open discussions since the super user can access personal details through the Drupal API calls and Spark DB.
5. To make sure no one enters by mistake, add a popup on login load - "This is Midburn Tech's Development Environment. If you are not from Midburn Tech, you should probably head to Spark Production (+button "Go to Spark")?

**Comment by amotenko** [comment]
https://spark.staging.midburn.org
