### ISSUE TITLE
Add profile id to the jwt payload

### ISSUE THREAD

**Issue by shaytidhar** [Midburn/spark#398]
#In order to identify logged in user on external modules, the jwt has to contain not only the mail but the profile_id.
the profile id key should be id.
for example, this is a vaild payload:
{
  "id": 2565,
  "email": "mc-shuli@zahav.net.il",
  "iat": 1495831880,
  "exp": 1495831880
}

**Comment by ArtyomKa** [comment]
The problem is a bit more complicated than that, unfortunately. Spartk-volunteeers api expects *profile_id* (drupal user id), but AFAIK this property is not stored in spark users table.

Possible solutions:
* store profile_id in users table, and send it on the payload. This requires modifying the users table and the login process.
* Use data stored in the spark users table, and thus eliminating the need to access drupal API to acquire the user details. This requires rewriting some part of the volunteers API implementation.

**Comment by ArtyomKa** [comment]
After talking with @shaytidhar on slack 
Seems like the only problem is the _get user roles_ api, so the best solution for now is to use email for that instead of the profile_id. This requires minimal changes to the rest of the code, and can be implemented rather easily.

**Comment by LeonFedotov** [comment]
@ArtyomKa this sounds reasnoble, @shaytidhar can you try and use email for now? lets see if it works?

**Comment by ArtyomKa** [comment]
Some leads on where to start:
* If we choose to implement using an email for _get_roles_ api. the code is in _volunteers_routes.js_ method _get_roles_ (somewhere about [here](https://github.com/Midburn/Spark/blob/master/routes/volunteers_routes.js#L28))
* If we wanna use pass profile_id in the cookie payload, then the relevant code is somewhere in the [login mechanism](https://github.com/Midburn/Spark/blob/master/routes/main_routes.js#L88)
