### ISSUE TITLE
standardize the migration and DB setup process

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#4]
Currently there are duplicated migrations:
* Knex - https://github.com/Midburn/Spark/tree/master/migrations
* .sql files - https://github.com/Midburn/Spark/tree/master/sql

Also, there is no standard simple way to run migration (at least from what I could see)

### TODO
* decide on which migration tool we are using and remove the other one
* create a standardized way to run the migrations - e.g. a bash file bin/run_mgrations.sh

**Comment by ripper234** [comment]
Odd. I translated the major schema to knex (because it's compatible with other databases including SQLite I introduced for testing). I thought I deleted the main schema.sql file, but apparently not.

Need to:

1. Synchronize any changes from schema.sql into migrations/20161208025453_init.js (knex)
2. Delete schema.sql
3. Check with the team if anyone needs the other SQL files in the sql/ folder (basically they shouldn't ... the initial data should all be in one file right now, and that file's format should be knex).
4. Mirgate the other files into 20161208025453_init.js knex + delete
5. Document how to work with knex migrations and inform the teams & team leads.

**Comment by ripper234** [comment]
BTW regarding your second TODO above: knex is the standard, pretty well documented.
If there's a need for a mini-script (not sure that there is), we can add it to the `scripts` section of package.json ... but I don't think we need an external bash script.

**Comment by OriHoch** [comment]
Cool, I'll do it

**Comment by OriHoch** [comment]
@ripper234  - opened a PR which switches to Knex, please review - #15

**Comment by OriHoch** [comment]
## Follow-up tasks:
* update documentation about how to use Knex and inform the team - #16
* use Sqlite by default for local development - #17
