### ISSUE TITLE
UI improvements to Spark - Manage Department Members

### ISSUE THREAD

**Issue by omerpines** [Midburn/spark#442]
Feature improvement on Department Volunteers.

### Description
See attached images for info. 

### Steps to Reproduce

![6](https://cloud.githubusercontent.com/assets/7349997/26365819/6dfca53a-3ff1-11e7-82c0-9fb376eda1b5.png)
![7](https://cloud.githubusercontent.com/assets/7349997/26365863/9b28fb44-3ff1-11e7-93d4-565631477fd3.png)

**Comment by arnonhecht** [comment]
I'm working on this

**Comment by amotenko** [comment]
@Yanipo5 did you find anything to do here?

**Comment by yaniv-peretz** [comment]
actually was delayed because with don't have the proper seed for the production-camp members... so I couldn't complete the work,
this is in part what I need to talk to @NitayRabi about...

Alex, reopen the issue if you think it is important, all the other requests are just label change could be done very quickly.

**Comment by amotenko** [comment]
Closing old issues and opening new UI issues:

https://github.com/Midburn/spark/issues/632
https://github.com/Midburn/spark/issues/633
https://github.com/Midburn/spark/issues/634
