### ISSUE TITLE
seeder.js 1_users - Duplicate entry '1' for key 'PRIMARY'

### ISSUE THREAD

**Issue by yaniv-peretz** [Midburn/spark#612]
seeder.js creates about 1000 users (which is good 👍 ), than stops with console log:
knex query-error: Error: ER_DUP_ENTRY: Duplicate entry '1' for key 'PRIMARY'
same happens on all seeder files.

might be that the seed is trying to loop back and create the initial user 1 again?
@NitayRabi  ?

**Comment by NitayRabi** [comment]
@Yanipo5  - I don't think it's about the looping maybe something with knex itself - but i'll have a look ASAP (tomorrow evening :) ). 
The data that is seeded works as expected?

**Comment by yaniv-peretz** [comment]
I can see the data on the MySql workbrench🖒.
But I did check on the GUI

**Comment by NitayRabi** [comment]
Hi, for some reason i cant push any branch to the midburn remote... 
But the problem was with the initial 0 id. I think knex has some if statement which ignores 0 (then creating `1` primary key for both 0 and 1 entries).
I'll see what i can do about permissions and create  a PR
See https://github.com/Midburn/spark/pull/614

**Comment by yaniv-peretz** [comment]
Hi Nitay succeeded in pushing/loading the Branch?
Our user_id is set to Auto Increment,
Therefore user_id=0 will result in a new user_id.
when creating new usersite it might be good to keep user_id=0 for all users.
