### ISSUE TITLE
Cannot download all files from spark (camp files)

### ISSUE THREAD

**Issue by MidburnThemeCamps** [Midburn/spark#707]
Clicking on "download all" in the new files module.

A .zip file starts downloading.

After a few seconds the download fails, getting a corrupt zip file.

Please fix?

Thanks!
Adir
Theme camps

**Comment by OriHoch** [comment]
@MidburnThemeCamps - I sent you the package in slack

## Procedure to download zip file manually
* Get AWS S3 credentials and write them to `~/.aws/config`
```
[profile midburn]
region = eu-west-1
aws_access_key_id=***
aws_secret_access_key=***
```
* `aws s3 --profile midburn sync s3://midburn-spark-camp-files-prod/ ./midburn-spark-camp-files-prod/`
* `zip -r ./midburn-spark-camp-files-prod.zip ./midburn-spark-camp-files-prod`

**Comment by ghost** [comment]
Fixed by e9df6bc

A race condition was created by larger network lag and less processing power and memory available in containers.
Fixed so that timing issues are less significant.

@MidburnThemeCamps Please note that the download is a little bit slow, but should complete successfully.

Feel free to reopen if you still have issues.

**Comment by OriHoch** [comment]
can increase the CPU

**Comment by ghost** [comment]
Don’t think there’s a need for that. 

Right now there shouldn’t be a race condition anymore and it does make the download slower, but since this is used once or twice a year, no point in investing additional effort IMHO

**Comment by OriHoch** [comment]
increasing the CPU is no effort..

**Comment by ghost** [comment]
I know, but switching back to async zipping and testing is :)
