### ISSUE TITLE
Managers can't add users to camps/art

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#745]
We have been receiving this feedback a lot but it is not consistent, i.e. comes and goes.

1. Find a specific user on a specific camp that cannot be added.
2. Make sure the user signed all the crap etc in the profile system.
3. Debug why user can't be added to the camp.

Ask @pandamichal for the user that is giving her trouble
https://www.facebook.com/groups/217022568848232/permalink/218072202076602/

**Comment by ArtyomKa** [comment]
Talked to Gil Burstein - Manager of one of the Art Installations that had problems (i.e. was not paying attention...) His volunteer was not in spark - I checked the users table. That's why he could not add him/her.
Also the problem is specific to art installations. Looks like theme camps do not have this constrained and they are added to the users if they are not there. I don't know why it was implemented this way.

**Comment by amotenko** [comment]
this is also fixed now, sorry don't have the pr
